author: mncat77
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.mncat77.tenjavacontestplugin.TenJavaContestPlugin
name: TenJavaContestPlugin
startup: postworld
version: '1.0'
